name: flutter_libserialport_example
description: Demonstrates how to use the flutter_libserialport plugin.
publish_to: 'none'

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport:
    path: ../

  material_ui: any
flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
